### ISSUE TITLE
Create DisplayMentorInfo depend on camp id

### ISSUE THREAD

**Issue by Omar-Alaa-Elzanaty** [Omar-Alaa-Elzanaty/ISc#11]
request url
/api/Leader/MentorInfo/{campId}

response body
{
  "isSuccess": true,
  "entity": [
    {
      "id": 1,
      "fullName": "omar"
    }
  ],
  "comment": null
}

**Comment by Omar-Alaa-Elzanaty** [comment]
Done
@Saeed-Ramadan

**Comment by Saeed-Ramadan** [comment]
done
